org: alejandrolopez1992
app: textatask
service: MorningQueryLambda

frameworkVersion: '3'


provider:
  name: aws
  runtime: python3.9

functions:
  cronHandler:
    handler: handler.run
    events:
      # Invoke Lambda function every day at 2:00 AM (UTC)
      - schedule: cron(0 14 ? * * *)
